name: IAC & APP Deployment and Cleanup

on:
  workflow_dispatch:
  push:
    branches:
      - main
      - dev-branch
    paths:
      - IAC/**
      - app/**
      - k8s/**
  pull_request:
    branches:
      - main
    paths:
      - IAC/**
      - app/**
      - k8s/**
  
jobs:
  terraform-construct:      
    name: Terraform Deployment
    runs-on: ubuntu-latest

    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      
      BUCKET_TF_STATE: ${{ secrets.BUCKET_TF_STATE }}
      AWS_REGION: us-east-1
      #KUBECONFIG: ~/.kube/
        
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: latest

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ env.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ env.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Initialize Terraform with S3 Backend
        id: tf-init
        run: terraform init   
        working-directory: IAC 

      - name: Validate Terraform Configuration
        run: terraform validate
        working-directory: IAC 

      - name: Generate Terraform Plan
        id: tfplan
        if: steps.tf-init.outcome == 'success'
        run: terraform plan -no-color -input=false -out=tf-plan
        working-directory: IAC
        
      - name: Apply Terraform Configuration
        id: tfapply
        if: steps.tfplan.outcome == 'success'
        run: terraform apply -auto-approve tf-plan
        working-directory: IAC

      - name: Get microk8s EC2 IP address
        id: kube-cluster-ip
        run: |
          echo $(terraform output -raw ec2_public_ip) > EC2_HOST
          echo $EC2_HOST
        
  Build-publish-app:
    name: App builder and publisher
    runs-on: ubuntu-latest
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      ECR_REPOSITORY: dprofileapp
      #K8S_CLUSTER: ---
      AWS_REGION: us-east-1
    
    steps:
      - name: code checkout
        uses: actions/checkout@v4

      - name: upload image to ECR
        uses: appleboy/docker-ecr-action@master
        with:
          access_key: ${{ secrets.AWS_ACCESS_KEY_ID }}
          secret_key:  ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          registry: ${{ secrets.REGISTRY }}
            # cache_from: ${{ secrets.cache }}
          repo: ${{ env.ECR_REPOSITORY }}
          region:  ${{ env.AWS_REGION}}
          auto_tag: true
          daemon_off: false
          dockerfile: ./Dockerfile
          context: .
          working-directory: app


      


      
      
     


          








    
