name: IAC & APP Deployment and Cleanup

on:
  workflow_dispatch:
  push:
    branches:
      - main
      - dev-branch
    paths:
      - IAC/**
      - app/**
  pull_request:
    branches:
      - main
    paths:
      - IAC/**
      - app/**
  
jobs:
  terraform-construct:
    name: Terraform Deployment
    runs-on: ubuntu-latest

    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      
      BUCKET_TF_STATE: ${{ secrets.BUCKET_TF_STATE }}
      AWS_REGION: us-east-1
      #KUBECONFIG: ~/.kube/
        
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: latest

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ env.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ env.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Initialize Terraform with S3 Backend
        id: tf-init
        run: terraform init   
        working-directory: IAC 

      - name: Validate Terraform Configuration
        run: terraform validate
        working-directory: IAC 

      - name: Generate Terraform Plan
        id: tfplan
        if: steps.tf-init.outcome == 'success'
        run: terraform plan -no-color -input=false -out=tf-plan
        working-directory: IAC
        
      - name: Apply Terraform Configuration
        id: tfapply
        if: steps.tfplan.outcome == 'success'
        run: terraform apply -auto-approve tf-plan
        working-directory: IAC

      - name: Get microk8s EC2 IP address
        id: kube-cluster-ip
        run: echo $(terraform output -raw ec2_public_ip) > EC2_HOST

      # - name: Setup SSH Key and Connect to EC2
      #   run: |
      #     # Create SSH directory
      #     mkdir -p ~/.ssh
      #     echo "${{secrets.EC2_PRIVATE_KEY}}" > ~/.ssh/id_rsa
      #     chmod 600 ~/.ssh/id_rsa

      #     # Add EC2 host to known hosts
      #     ssh-keyscan -H "$EC2_HOST" >> ~/.ssh/known_hosts

      - name: Copy MicroK8s Kubeconfig from EC2
        run: |
          scp -i ${{secrets.EC2_PRIVATE_KEY}} ubuntu@EC2_HOST:~/.kube/config ~/.kube/config
          chmod 600 ~/.kube/config

      - name: Try Kubernetes cli command from here
        run: microk8s kubectl get ns

    


      

#-------------------------------------------------------------#

    

      # - name: Get microk8s ec2 instance ip address
      #   run: echo $(terraform output -raw ec2_public_ip) > EC2_HOST.txt
      #   working-directory: IAC

      # - name: Upload EC2_HOST.txt File as Artifact
      #   uses: actions/upload-artifact@v4
      #   with:
      #     name: microk8s-ip
      #     path: EC2_HOST.txt
        
      
  # setup-kubeconfig:
  #   name: Setup Kubeconfig from microk8s EC2 instance
  #   runs-on: ubuntu-latest
  #   needs: terraform-construct

  #   env:
  #     AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  #     AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      
  #     BUCKET_TF_STATE: ${{ secrets.BUCKET_TF_STATE }}
  #     LOCAL_KUBECONFIG: "$HOME/.kube/config"
  #     AWS_REGION: us-east-1

  #   steps:
  #   - name: Checkout Repository
  #     uses: actions/checkout@v4

  #   - name: Download EC2_HOST.txt File
  #     uses: actions/download-artifact@v4
  #     with:
  #       name: microk8s-ip

  #   - name: Read and Export Variable
  #     run: |
  #         source EC2_HOST.txt
  #         cat EC2_HOST.txt >> $EC2_HOST
  #   - name: Create ~/.kube Directory
  #     run: mkdir -p ~/.kube

  #   - name: Setup SSH Key and Connect to EC2
  #     run: |
  #         # Create SSH directory
  #         mkdir -p ~/.ssh
  #         echo "${{secrets.EC2_PRIVATE_KEY}}" > ~/.ssh/id_rsa
  #         chmod 600 ~/.ssh/id_rsa

  #         # Add EC2 host to known hosts
  #         ssh-keyscan -H "$EC2_HOST" >> ~/.ssh/known_hosts  

  #   - name: Copy MicroK8s Kubeconfig from EC2
  #     run: |
  #         scp -i ${{secrets.EC2_PRIVATE_KEY}} ubuntu@EC2_HOST:/var/snap/microk8s/current/credentials/client.config ~/.kube/config
  #         chmod 600 ~/.kube/config

  #   - name: Export KUBECONFIG for Workflow
  #     run: echo "KUBECONFIG=$HOME/.kube/config" >> $GITHUB_ENV


       
  # Cleanup:
  #   name: Terraform Destroy
  #   runs-on: ubuntu-latest
  #   needs: terraform-construct
  #   if: github.event_name == 'workflow_dispatch'
  #   env:
  #     AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  #     AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      
  #     BUCKET_TF_STATE: ${{ secrets.BUCKET_TF_STATE }}
  #     AWS_REGION: us-east-1
          
  #   steps:
  #     - name: Checkout Repository
  #       uses: actions/checkout@v4

  #     - name: Setup Terraform
  #       uses: hashicorp/setup-terraform@v3
  #       with:
  #         terraform_version: latest
  
  #     - name: Configure AWS Credentials
  #       uses: aws-actions/configure-aws-credentials@v4
  #       with:
  #         aws-access-key-id: ${{ env.AWS_ACCESS_KEY_ID }}
  #         aws-secret-access-key: ${{ env.AWS_SECRET_ACCESS_KEY }}
  #         aws-region: ${{ env.AWS_REGION }}    

  #     - name: Initialize Terraform with S3 Backend
  #       id: tf-init
  #       run: terraform init   
  #       working-directory: IAC 

  #     - name: Destroy Terraform Resources
  #       run: terraform destroy -auto-approve
  #       working-directory: IAC
      
      
     


          








    
